---
- name: "RSYSLOG - Install required packages"
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - "rsyslog"
    - "rsyslog-gnutls"
  tags:
    - install

- name: "RSYSLOG - Ensure that directory are created"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop: "{{ rsyslog_dirs }}"

- name: "RSYSLOG - Copy rsyslog configuration files"
  copy:
    src: "{{ item.src }}"
    dest: "/etc/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ rsyslog_files }}"
  notify: "restart rsyslog"
  tags:
    - configuration

- name: "RSYSLOG - Create rsyslog configuration files from template"
  template:
    src: "{{ item.src }}.j2"
    dest: "/etc/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ rsyslog_templates }}"
  notify: "restart rsyslog"
  tags:
    - configuration